# Generated by cucumber-sinatra. (Thu Jun 17 12:25:03 +1000 2010)

require File.join(File.dirname(__FILE__), '..', '..', 'lib/postbin.rb')

require 'capybara'
require 'capybara/cucumber'
require 'spec'
require 'rack/test'

def app
  PostBin::App  
end
World(Rack::Test::Methods)

PostBin::App.set(:environment, :test)

World do
  Capybara.app = PostBin::App
  include Capybara
  include Spec::Expectations
  include Spec::Matchers
end
